In [2]:
import numpy as np

# 1.

In [2]:
x=np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# 2.

In [3]:
x[4]=1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

# 3.

In [4]:
a=np.vstack((np.arange(0,3),np.arange(3,6),np.arange(6,9)))
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# 4.

In [5]:
np.random.random((3,3,3))

array([[[0.23328745, 0.30868479, 0.28853104],
        [0.84629394, 0.22356   , 0.67120513],
        [0.38632182, 0.62522996, 0.78688639]],

       [[0.77136329, 0.69485848, 0.24184711],
        [0.88781405, 0.57932773, 0.01047064],
        [0.37218716, 0.14946934, 0.64129374]],

       [[0.36649361, 0.41194485, 0.45706364],
        [0.40250901, 0.19337302, 0.32226896],
        [0.70047832, 0.9544019 , 0.47293522]]])

# 5.

In [6]:
np.dot(np.random.random((5,3)),np.random.random((3,2)))

array([[0.53907019, 0.46168374],
       [0.26668352, 0.30411365],
       [0.43431715, 0.31389288],
       [0.81117339, 0.62437152],
       [0.27427528, 0.33336055]])

# 6.

In [7]:
np.vstack((np.arange(0,5),np.arange(0,5),np.arange(0,5),np.arange(0,5),np.arange(0,5)))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

# 7.

In [8]:
j=[0,1,2]
for i in j:
    a=a-a.mean(axis=1)[i] #array created in question 3
print(a)    

[[-7. -6. -5.]
 [-4. -3. -2.]
 [-1.  0.  1.]]


# 8.

In [4]:
b=np.dot(np.vstack((np.arange(0,3),np.arange(3,6),np.arange(6,9))),np.vstack((np.arange(0,3),np.arange(3,6),np.arange(6,9))))
print(b)
i=0
while i<3:
    print(b[i][i])
    i+=1

[[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]]
15
54
111


# 9.

In [10]:
z=np.ones(3,dtype=int)
print(z)

[1 1 1]


In [11]:
np.bincount(z).argmax()

1

# 10.

In [12]:
x=np.random.random(10)
x.sort()
print(x)

[0.18230924 0.38583722 0.43271168 0.51170395 0.5252515  0.8640232
 0.89452873 0.90296197 0.91618951 0.94816292]


# PANDAS 

In [13]:
import pandas as pd

# 1.

In [94]:
chipo=pd.read_csv("C:\\Users\\Jayesh's\\Desktop\\Pyhton_Notebooks\\datasets\\chipotle.tsv",delimiter='	')

# 2.

In [128]:
chipo[:10]

order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa   
1         1         1                                   Izze   
2         1         1                       Nantucket Nectar   
3         1         1  Chips and Tomatillo-Green Chili Salsa   
4         2         2                           Chicken Bowl   
5         3         1                           Chicken Bowl   
6         3         1                          Side of Chips   
7         4         1                          Steak Burrito   
8         4         1                       Steak Soft Tacos   
9         5         1                          Steak Burrito   

                                  choice_description  item_price  
0                                                NaN        2.39  
1                                       [Clementine]        3.39  
2                                            [Apple]        3.39  
3                                                NaN        2.39  
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...       16.98  
5  [Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...       10.98  
6                                                NaN        1.69  
7  [Tomatillo Red Chili Salsa, [Fajita Vegetables...       11.75  
8  [Tomatillo Green Chili Salsa, [Pinto Beans, Ch...        9.25  
9  [Fresh Tomato Salsa, [Rice, Black Beans, Pinto...        9.25

# 3 & 4.

In [96]:
chipo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
order_id              4622 non-null int64
quantity              4622 non-null int64
item_name             4622 non-null object
choice_description    3376 non-null object
item_price            4622 non-null object
dtypes: int64(2), object(3)
memory usage: 180.6+ KB


#### 4622 observations  and 5 columns

# 5.

In [97]:
chipo.columns

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='object')

# 6.

In [98]:
chipo.index

RangeIndex(start=0, stop=4622, step=1)

# 7.

In [99]:
chipo['item_name'].value_counts() # chicken bowl most ordered

Chicken Bowl                             726
Chicken Burrito                          553
Chips and Guacamole                      479
Steak Burrito                            368
Canned Soft Drink                        301
Steak Bowl                               211
Chips                                    211
Bottled Water                            162
Chicken Soft Tacos                       115
Chicken Salad Bowl                       110
Chips and Fresh Tomato Salsa             110
Canned Soda                              104
Side of Chips                            101
Veggie Burrito                            95
Barbacoa Burrito                          91
Veggie Bowl                               85
Carnitas Bowl                             68
Barbacoa Bowl                             66
Carnitas Burrito                          59
Steak Soft Tacos                          55
6 Pack Soft Drink                         54
Chips and Tomatillo Red Chili Salsa       48
Chicken Cr

# 8.

In [100]:
mf = (chipo['item_name'] =='Chicken Bowl')
chipo[mf].quantity.sum()

761

# 9.

In [101]:
chipo['choice_description'].value_counts() # diet coke 

[Diet Coke]                                                                                                                       134
[Coke]                                                                                                                            123
[Sprite]                                                                                                                           77
[Fresh Tomato Salsa, [Rice, Black Beans, Cheese, Sour Cream, Lettuce]]                                                             42
[Fresh Tomato Salsa, [Rice, Black Beans, Cheese, Sour Cream, Guacamole, Lettuce]]                                                  40
[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice, Cheese, Sour Cream]]                                                               36
[Fresh Tomato Salsa, [Rice, Black Beans, Cheese, Sour Cream]]                                                                      33
[Lemonade]                                                    

# 10.

In [108]:
chipo.quantity.sum() # total quantity

4972

# 11.

In [103]:
chipo['item_price'] = chipo['item_price'].str.replace('$','')  
chipo['item_price'] = chipo['item_price'].astype(float)
chipo['item_price']

0        2.39
1        3.39
2        3.39
3        2.39
4       16.98
5       10.98
6        1.69
7       11.75
8        9.25
9        9.25
10       4.45
11       8.75
12       8.75
13      11.25
14       4.45
15       2.39
16       8.49
17       8.49
18       2.18
19       8.75
20       4.45
21       8.99
22       3.39
23      10.98
24       3.39
25       2.39
26       8.49
27       8.99
28       1.09
29       8.49
        ...  
4592    11.75
4593    11.75
4594    11.75
4595     8.75
4596     4.45
4597     1.25
4598     1.50
4599     8.75
4600     4.45
4601     1.25
4602     9.25
4603     9.25
4604     8.75
4605     4.45
4606     1.25
4607    11.75
4608    11.25
4609     1.25
4610    11.75
4611    11.25
4612     9.25
4613     2.15
4614     1.50
4615     8.75
4616     4.45
4617    11.75
4618    11.75
4619    11.25
4620     8.75
4621     8.75
Name: item_price, Length: 4622, dtype: float64

# 12.

In [104]:
chipo['item_price'].dtype

dtype('float64')

# 13.

In [109]:
chipo.item_price.sum()

34500.16

# 14.

In [124]:
chipo.item_name.value_counts().count()

50

# 15.

In [132]:
chipo['quantity'].sum()

4972

# 16.

In [133]:
chipo['item_price'].mean()

7.464335785374397