In [13]:
from sklearn.tree import DecisionTreeClassifier as dtc
from sklearn import datasets
iris=datasets.load_iris()
X=iris.data
y=iris.target
from sklearn.model_selection import train_test_split as t_t_s
X_train,X_test,y_train,y_test=t_t_s(X,y,test_size=0.2,random_state=38)
dt=dtc()
dt.fit(X_train,y_train)
predictions=dt.predict(X_test)
dt.score(X_test,y_test)

1.0

In [14]:
print(predictions)
print(y_test)

correct_value = predictions == y_test
print(correct_value)

correct_value.sum() / correct_value.shape


[0 2 2 0 2 1 1 2 1 2 0 2 1 1 1 2 1 2 2 2 0 1 0 0 2 0 1 0 0 1]
[0 2 2 0 2 1 1 2 1 2 0 2 1 1 1 2 1 2 2 2 0 1 0 0 2 0 1 0 0 1]
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True]


array([1.])

In [15]:
dt
import numpy as np

In [16]:
from matplotlib.colors import ListedColormap

In [17]:
def plot_decision_regions(X, y, classifier, resolution=0.02):

    # setup marker generator and color map
    markers = ('s', 'x', 'o', '^', 'v')
    colors = ('red', 'blue', 'lightgreen', 'gray', 'cyan')
    cmap = ListedColormap(colors[:len(np.unique(y))])

    # plot the decision surface
    x1_min, x1_max = X[:, 0].min() - 1, X[:, 0].max() + 1
    x2_min, x2_max = X[:, 1].min() - 1, X[:, 1].max() + 1
    xx1, xx2 = np.meshgrid(np.arange(x1_min, x1_max, resolution),
                           np.arange(x2_min, x2_max, resolution))
    Z = classifier.predict(np.array([xx1.ravel(), xx2.ravel()]).T)
    Z = Z.reshape(xx1.shape)
    plt.contourf(xx1, xx2, Z, alpha=0.3, cmap=cmap)
    plt.xlim(xx1.min(), xx1.max())
    plt.ylim(xx2.min(), xx2.max())

    # plot class samples
    for idx, cl in enumerate(np.unique(y)):
        plt.scatter(x=X[y == cl, 0],
                    y=X[y == cl, 1],
                    alpha=0.8,
                    c=colors[idx],
                    marker=markers[idx],
                    label=cl,
                    edgecolor='black')

In [20]:
import matplotlib.pyplot as plt
%matplotlib inline
clf = dtc()
clf.fit(X_train,y_train)
XX = X_train[:,:2]

plot_decision_regions(XX, y_train, dt)

ValueError: Number of features of the model must match the input. Model n_features is 4 and input n_features is 2 

# 0-------------

# Assignment

In [26]:
import pandas as pd
wbc=pd.read_csv("C:\\Users\\Jayesh's\\Desktop\\Pyhton_Notebooks\\datasets\\wbc.csv")
wbc.head(100)
#wbc.shape

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0     842302         M       17.990         10.38          122.80     1001.0   
1     842517         M       20.570         17.77          132.90     1326.0   
2   84300903         M       19.690         21.25          130.00     1203.0   
3   84348301         M       11.420         20.38           77.58      386.1   
4   84358402         M       20.290         14.34          135.10     1297.0   
5     843786         M       12.450         15.70           82.57      477.1   
6     844359         M       18.250         19.98          119.60     1040.0   
7   84458202         M       13.710         20.83           90.20      577.9   
8     844981         M       13.000         21.82           87.50      519.8   
9   84501001         M       12.460         24.04           83.97      475.9   
10    845636         M       16.020         23.24          102.70      797.8   
11  84610002         M       15.780         17.89          103.60      781.0   
12    846226         M       19.170         24.80          132.40     1123.0   
13    846381         M       15.850         23.95          103.70      782.7   
14  84667401         M       13.730         22.61           93.60      578.3   
15  84799002         M       14.540         27.54           96.73      658.8   
16    848406         M       14.680         20.13           94.74      684.5   
17  84862001         M       16.130         20.68          108.10      798.8   
18    849014         M       19.810         22.15          130.00     1260.0   
19   8510426         B       13.540         14.36           87.46      566.3   
20   8510653         B       13.080         15.71           85.63      520.0   
21   8510824         B        9.504         12.44           60.34      273.9   
22   8511133         M       15.340         14.26          102.50      704.4   
23    851509         M       21.160         23.04          137.20     1404.0   
24    852552         M       16.650         21.38          110.00      904.6   
25    852631         M       17.140         16.40          116.00      912.7   
26    852763         M       14.580         21.53           97.41      644.8   
27    852781         M       18.610         20.25          122.10     1094.0   
28    852973         M       15.300         25.27          102.40      732.4   
29    853201         M       17.570         15.05          115.00      955.1   
..       ...       ...          ...           ...             ...        ...   
70    859575         M       18.940         21.31          123.60     1130.0   
71    859711         B        8.888         14.64           58.79      244.0   
72    859717         M       17.200         24.52          114.20      929.4   
73    859983         M       13.800         15.79           90.43      584.1   
74   8610175         B       12.310         16.52           79.19      470.9   
75   8610404         M       16.070         19.65          104.10      817.7   
76   8610629         B       13.530         10.94           87.91      559.2   
77   8610637         M       18.050         16.15          120.20     1006.0   
78   8610862         M       20.180         23.97          143.70     1245.0   
79   8610908         B       12.860         18.00           83.19      506.3   
80    861103         B       11.450         20.97           73.81      401.5   
81   8611161         B       13.340         15.86           86.49      520.0   
82   8611555         M       25.220         24.91          171.50     1878.0   
83   8611792         M       19.100         26.29          129.10     1132.0   
84   8612080         B       12.000         15.65           76.95      443.3   
85   8612399         M       18.460         18.52          121.10     1075.0   
86  86135501         M       14.480         21.46           94.25      648.2   
87  86135502         M       19.020         24.59          122.00     1076.0   
88    8615

In [14]:
wbc.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='object')

In [28]:
wbc.diagnosis.unique()

array(['M', 'B'], dtype=object)

In [15]:
wbc_n = pd.get_dummies(wbc)
wbc_n=wbc_n.drop('Unnamed: 32', axis=1)

In [27]:
wbc_n.head(100)

id  radius_mean  texture_mean  perimeter_mean  area_mean  \
0     842302       17.990         10.38          122.80     1001.0   
1     842517       20.570         17.77          132.90     1326.0   
2   84300903       19.690         21.25          130.00     1203.0   
3   84348301       11.420         20.38           77.58      386.1   
4   84358402       20.290         14.34          135.10     1297.0   
5     843786       12.450         15.70           82.57      477.1   
6     844359       18.250         19.98          119.60     1040.0   
7   84458202       13.710         20.83           90.20      577.9   
8     844981       13.000         21.82           87.50      519.8   
9   84501001       12.460         24.04           83.97      475.9   
10    845636       16.020         23.24          102.70      797.8   
11  84610002       15.780         17.89          103.60      781.0   
12    846226       19.170         24.80          132.40     1123.0   
13    846381       15.850         23.95          103.70      782.7   
14  84667401       13.730         22.61           93.60      578.3   
15  84799002       14.540         27.54           96.73      658.8   
16    848406       14.680         20.13           94.74      684.5   
17  84862001       16.130         20.68          108.10      798.8   
18    849014       19.810         22.15          130.00     1260.0   
19   8510426       13.540         14.36           87.46      566.3   
20   8510653       13.080         15.71           85.63      520.0   
21   8510824        9.504         12.44           60.34      273.9   
22   8511133       15.340         14.26          102.50      704.4   
23    851509       21.160         23.04          137.20     1404.0   
24    852552       16.650         21.38          110.00      904.6   
25    852631       17.140         16.40          116.00      912.7   
26    852763       14.580         21.53           97.41      644.8   
27    852781       18.610         20.25          122.10     1094.0   
28    852973       15.300         25.27          102.40      732.4   
29    853201       17.570         15.05          115.00      955.1   
..       ...          ...           ...             ...        ...   
70    859575       18.940         21.31          123.60     1130.0   
71    859711        8.888         14.64           58.79      244.0   
72    859717       17.200         24.52          114.20      929.4   
73    859983       13.800         15.79           90.43      584.1   
74   8610175       12.310         16.52           79.19      470.9   
75   8610404       16.070         19.65          104.10      817.7   
76   8610629       13.530         10.94           87.91      559.2   
77   8610637       18.050         16.15          120.20     1006.0   
78   8610862       20.180         23.97          143.70     1245.0   
79   8610908       12.860         18.00           83.19      506.3   
80    861103       11.450         20.97           73.81      401.5   
81   8611161       13.340         15.86           86.49      520.0   
82   8611555       25.220         24.91          171.50     1878.0   
83   8611792       19.100         26.29          129.10     1132.0   
84   8612080       12.000         15.65           76.95      443.3   
85   8612399       18.460         18.52          121.10     1075.0   
86  86135501       14.480         21.46           94.25      648.2   
87  86135502       19.020         24.59          122.00     1076.0   
88    861597       12.360         21.80           79.78      466.1   
89    861598       14.640         15.24           95.77      651.9   
90    861648       14.620         24.02           94.57      662.7   
91    861799       15.370         22.76          100.20      728.2   
92    861853       13.270         14.76           84.74      551.7   
93    862009       13.450         18.30           86.60      555.1   
94    862028       15.060         19.83          100.30      705.6   
95     86208       2

In [49]:
from sklearn.tree import DecisionTreeClassifier as dtc
X = wbc_n.drop("diagnosis_B",axis = 1).values
y = wbc_n["diagnosis_B"].values
X_train,X_test,y_train,y_test=t_t_s(X,y,test_size=0.43,random_state=48)
dt=dtc()
dt.fit(X_train,y_train)
prediction=dt.predict(X_test)
dt.score(X_test,y_test)

1.0

In [48]:
print(predictions)
print(y_test)

#correct_value = predictions == y_test
#print(correct_value)

#correct_value.sum() / correct_value.shape


[0 2 2 0 2 1 1 2 1 2 0 2 1 1 1 2 1 2 2 2 0 2 0 0 2 0 1 0 0 1]
[0.1678  0.1254  0.1076  0.1227  0.09267 0.1271  0.1139  0.1108  0.1087
 0.1478  0.1282  0.153   0.1021  0.08774 0.1037  0.119   0.1304  0.1306
 0.1789  0.1471  0.139   0.1124  0.1101  0.1313  0.1873  0.09862 0.1316
 0.1419  0.112   0.1391  0.1275  0.1017  0.1432  0.1316  0.1411  0.1385
 0.1415  0.1226  0.1036  0.1416  0.1312  0.1341  0.1374  0.1234  0.09983
 0.128   0.1223  0.1388  0.1381  0.1223  0.1411  0.166   0.1297  0.1637
 0.1297  0.158   0.1311  0.1434  0.1292  0.1464  0.1377  0.1256  0.1681
 0.1104  0.1143  0.1275  0.1126  0.1176  0.1326  0.1278  0.1162  0.09203
 0.1077  0.1073  0.08567 0.1639  0.1265  0.1541  0.1016  0.1026  0.1376
 0.1233  0.144   0.1247  0.1352  0.1376  0.146   0.1525  0.146   0.1134
 0.1126  0.1641  0.1277  0.1276  0.1369  0.1786  0.1349  0.164   0.1446
 0.1072  0.08125 0.1324  0.1288  0.1351  0.1118  0.1105  0.1878  0.1499
 0.1401  0.1463  0.13    0.1562  0.1368  0.1401  0.1547  0.1512  0.1213


In [44]:
from sklearn.linear_model import LinearRegression as dtc
X = wbc_n.drop("smoothness_worst",axis = 1).values
y = wbc_n["smoothness_worst"].values
X_train,X_test,y_train,y_test=t_t_s(X,y,test_size=0.32,random_state=28)
dt=dtc()
dt.fit(X_train,y_train)
prediction=dt.predict(X_test)
dt.score(X_test,y_test)

0.8773022285733582